name: Conflictor runner

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: master
          fetch-depth: 0
      - name: Start conflict analyzer
        uses: shpingalet007/conflictor@workflows
        with:
          repository: ${{ github.event.repository.full_name }}
          deploy-label: 'deploy state: ✅ done'
          main-branch: 'master'
