name: Conflictor runner

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Conflictor runner
        uses: shpingalet007/conflictor@v0.1.3.003
        with:
          repository: ${{ github.event.repository.full_name }}
          deploy-label: 'deploy state: ✅ done'
